/* SPDX-License-Identifier: GPL-2.0-or-later
 * Copyright (c) 2022 Hansem Ro <hansemro@outlook.com>
 */

#pragma once

#include "pin_defs.h"

#define DEBUG_MATRIX_SCAN_RATE

#define DRIVER_LED_TOTAL 108

/* MBI5042 */
#define MBI5042_NUM_CASCADE 1
#define MBI5042_LE_PIN A15
#define MBI5042_SDI_PIN C12
#define MBI5042_SDO_PIN B0
#define MBI5042_DCLK_PIN A14
#define MBI5042_GCLK_PIN C10
#define MBI5042_HAS_POWER_PIN
#define MBI5042_PWRCTRL_PIN C11

#define LED_ROW_PINS \
    { C15, C14, B5, B4, B3, B2, D3, D2 }

#ifdef LED_MATRIX_ENABLE
#    define LED_MATRIX_KEYPRESSES          // reacts to keypresses
#    define LED_MATRIX_KEYRELEASES         // reacts to keyreleases (instead of keypresses)
#    define LED_MATRIX_FRAMEBUFFER_EFFECTS // enable framebuffer effects
#    define ENABLE_LED_MATRIX_ALPHAS_MODS
#    define ENABLE_LED_MATRIX_BREATHING
#    define ENABLE_LED_MATRIX_BAND
#    define ENABLE_LED_MATRIX_BAND_PINWHEEL
#    define ENABLE_LED_MATRIX_BAND_SPIRAL
#    define ENABLE_LED_MATRIX_CYCLE_LEFT_RIGHT
#    define ENABLE_LED_MATRIX_CYCLE_UP_DOWN
#    define ENABLE_LED_MATRIX_CYCLE_OUT_IN
#    define ENABLE_LED_MATRIX_DUAL_BEACON
#    define ENABLE_LED_MATRIX_WAVE_LEFT_RIGHT
#    define ENABLE_LED_MATRIX_WAVE_UP_DOWN
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_SIMPLE
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_WIDE
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTIWIDE
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_CROSS
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTICROSS
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_NEXUS
#    define ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTINEXUS
#    define ENABLE_LED_MATRIX_SOLID_SPLASH
#    define ENABLE_LED_MATRIX_SOLID_MULTISPLASH
#endif
