# MCU
MCU = cortex-m3
ARMV = 7
USE_FPU = no
MCU_FAMILY = HT32
MCU_SERIES = HT32F165x
MCU_LDSCRIPT = HT32F1654_POK3RRGB
MCU_STARTUP = ht32f165x

# Wear-leveling driver
#EEPROM_DRIVER = wear_leveling
#WEAR_LEVELING_DRIVER = spi_flash
